version: '3'

services:
  DEDOV_214_1:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: DEDOV_214_1
      POSTGRES_USER: DEDOV_214_1
      POSTGRES_DB: DEDOV_214_1
    ports:
      - "5433:5432"
    volumes:
      - ./docker/db/scripts/DEDOV_214_1:/docker-entrypoint-initdb.d/
      - DEDOV_214_1_DATA:/postgresql

  DEDOV_214_2:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: DEDOV_214_2
      POSTGRES_USER: DEDOV_214_2
      POSTGRES_DB: DEDOV_214_2
    ports:
      - "5434:5432"
    volumes:
      - ./docker/db/scripts/DEDOV_214_2:/docker-entrypoint-initdb.d/
      - DEDOV_214_2_DATA:/postgresql

  DEDOV_214_3:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: DEDOV_214_3
      POSTGRES_USER: DEDOV_214_3
      POSTGRES_DB: DEDOV_214_3
    ports:
      - "5435:5432"
    volumes:
      - ./docker/db/scripts/DEDOV_214_3:/docker-entrypoint-initdb.d/
      - DEDOV_214_3_DATA:/postgresql

volumes:
  DEDOV_214_1_DATA:
    driver: local
  DEDOV_214_2_DATA:
    driver: local
  DEDOV_214_3_DATA:
    driver: local
